INSERT INTO L01_ESTADO (SIGLA, NOME)
VALUES ('SP',
        'SAO PAULO') ;


INSERT INTO L01_ESTADO (SIGLA, NOME)
VALUES ('RJ',
        'RIO DE JANEIRO') ;


INSERT INTO L02_CIDADE (NOME, SGLESTADO, POPULACAO )
VALUES ('SANTOS' ,
        'SP',
        15 );


INSERT INTO L02_CIDADE (NOME, SGLESTADO, POPULACAO )
VALUES ('MOGI DAS CRUZES' ,
        'SP',
        15 );


INSERT INTO L03_ZONA ( NOMECIDADE )
VALUES ( 'SANTOS' );


INSERT INTO L03_ZONA ( NOMECIDADE )
VALUES ( 'MOGI DAS CRUZES' );


INSERT INTO L04_BAIRRO ( CEP, NROZONA, NOMECIDADE, NOME )
VALUES (70373010,
        1,
        'SANTOS',
        'Vila Belmiro' );


INSERT INTO L04_BAIRRO ( CEP, NROZONA, NOMECIDADE, NOME )
VALUES (70373020,
        2,
        'MOGI DAS CRUZES',
        'Bairro do Neymar' );


INSERT INTO L05_URNA (NSERIAL, NROZONA, ESTADO )
VALUES (1,
        1,
        NULL );


INSERT INTO L05_URNA (NSERIAL, NROZONA, ESTADO )
VALUES (2,
        2,
        NULL );


INSERT INTO L06_SESSAO (NSERIAL, NROZONA )
VALUES (1,
        1 );


INSERT INTO L06_SESSAO (NSERIAL, NROZONA )
VALUES (2,
        2 );


INSERT INTO L07_PLEITO ( L02_CIDADE_NOME, ANO )
VALUES ( 'SANTOS',
         1991 );

INSERT INTO L07_PLEITO ( L02_CIDADE_NOME, ANO )
VALUES ( 'MOGI DAS CRUZES',
         1994 );

INSERT INTO L08_PARTIDO (SIGLA, NOME )
VALUES ('PT',
        'Partido dos Tios' );


INSERT INTO L08_PARTIDO (SIGLA, NOME )
VALUES ('PV',
        'Partido Viagem' );


INSERT INTO L09_CANDIDATO ( SGLPARTIDO, TIPO, CPF, NOME, IDADE, APELIDO, FOTO, IMPRESSAODIGITAL )
VALUES ( 'PT',
         'Politico',
         '12132123',
         'Potiguara',
         24,
         'Potigua',
         EMPTY_BLOB(),
         EMPTY_BLOB());


INSERT INTO L09_CANDIDATO ( SGLPARTIDO, TIPO, CPF, NOME, IDADE, APELIDO, FOTO, IMPRESSAODIGITAL )
VALUES ( 'PV',
         'Politico',
         '456123',
         'Tomioka',
         24,
         'Japa',
         EMPTY_BLOB(),
         EMPTY_BLOB());


INSERT INTO L10_CARGO ( POSSUIVICE, ANOBASE, ANOSMANDATO, NOMEDESCRITIVO, NROCADEIRAS, ESFERA )
VALUES ( 0,
         1990,
         4,
         'Governador',
         1,
         'Estadual' );


INSERT INTO L10_CARGO ( POSSUIVICE, ANOBASE, ANOSMANDATO, NOMEDESCRITIVO, NROCADEIRAS, ESFERA )
VALUES ( 0,
         1994,
         4,
         'Presidente',
         1,
         'Federal' );


INSERT INTO L11_CANDIDATURA ( ANO, CODCARGO, NROCANDIDATO )
VALUES ( 1994,
         1,
         1 );


INSERT INTO L11_CANDIDATURA ( ANO, CODCARGO, NROCANDIDATO )
VALUES ( 1990,
         2,
         2 );


INSERT INTO L12_PESQUISA ( PERIODOINICIO, PERIODOFIM, ORGAOPESQUISA )
VALUES ( to_date('01/01/1990','dd/mm/rrrr'),
         to_date('01/01/1994','dd/mm/rrrr'),
         'PEDROPE' );


INSERT INTO L12_PESQUISA ( PERIODOINICIO, PERIODOFIM, ORGAOPESQUISA )
VALUES ( to_date('01/01/1990','dd/mm/rrrr'),
         to_date('01/01/1992','dd/mm/rrrr'),
         'PEDROPE2' );


INSERT INTO L13_PLEITOCANDIDATURA (CODPLEITO, REGCANDIDATO )
VALUES (2,
        1 );


INSERT INTO L13_PLEITOCANDIDATURA (CODPLEITO, REGCANDIDATO )
VALUES (2,
        2 );


INSERT INTO L14_COMPUTAVOTOS ( CODPLEITO, SESSAONRO, REGCANDIDATURA, TOTAL )
VALUES ( 2,
         1,
         1,
         10 );


INSERT INTO L14_COMPUTAVOTOS ( CODPLEITO, SESSAONRO, REGCANDIDATURA, TOTAL )
VALUES ( 2,
         2,
         1,
         15 );


INSERT INTO L15_COMPUTAINTENCAOVOTOS ( REGCANDIDATURA, REGPESQUISA, TOTAL )
VALUES ( 1,
         1,
         50 );


INSERT INTO L15_COMPUTAINTENCAOVOTOS ( REGCANDIDATURA, REGPESQUISA, TOTAL )
VALUES ( 2,
         1,
         50 );
