CREATE OR REPLACE FUNCTION FN_CLASSIFICACAO(
P_DATA IN DATE

)
RETURN T_RET_CLASSIFICACAO

IS

V_RETORNO T_RET_CLASSIFICACAO;
V_CONT 	NUMBER DEFAULT 0;
V_PONTUACAO      NUMBER;
V_QTD_JOGOS      NUMBER;
V_QTD_VITORIAS   NUMBER;
V_QTD_EMPATES    NUMBER;
V_QTD_DERROTAS   NUMBER;
V_GOLS_PRO       NUMBER;
V_GOLS_CONTRA    NUMBER;
V_GOLS_SALDO     NUMBER;
V_APROVEITAMENTO NUMBER;


BEGIN
  
-- inicializa v_retorno
V_RETORNO := T_RET_CLASSIFICACAO();

	FOR C_EQUIPES IN (SELECT * FROM EQUIPE ) LOOP
		
		V_PONTUACAO := PKG_TABELA.FN_PONTUACAO_EQUIPE(C_EQUIPES.COD_EQUIPE, P_DATA);
		V_QTD_JOGOS := PKG_TABELA.FN_QTD_JOGOS_EQUIPE(C_EQUIPES.COD_EQUIPE, P_DATA);
		V_QTD_VITORIAS := PKG_TABELA.FN_VITORIA_EQUIPE(C_EQUIPES.COD_EQUIPE, P_DATA);
		V_QTD_EMPATES := PKG_TABELA.FN_EMPATE_EQUIPE(C_EQUIPES.COD_EQUIPE, P_DATA);
		V_QTD_DERROTAS := PKG_TABELA.FN_DERROTA_EQUIPE(C_EQUIPES.COD_EQUIPE, P_DATA);
		V_GOLS_PRO := PKG_TABELA.FN_GOL_PRO_EQUIPE(C_EQUIPES.COD_EQUIPE, P_DATA);
		V_GOLS_CONTRA := PKG_TABELA.FN_GOL_CONTRA_EQUIPE(C_EQUIPES.COD_EQUIPE, P_DATA);
		V_GOLS_SALDO := PKG_TABELA.FN_SALDO_GOL_EQUIPE(C_EQUIPES.COD_EQUIPE, P_DATA);
		V_APROVEITAMENTO := PKG_TABELA.FN_APROVEITAMENTO_EQUIPE(C_EQUIPES.COD_EQUIPE, P_DATA);

		-- Aloca espaço para a linha
		V_RETORNO.EXTEND;
		-- Incrementa contador
		V_CONT := V_CONT + 1;
		-- Insere objeto na tabela temporária na posicao 'V_CONT'
		V_RETORNO(V_CONT) := T_OBJ_CLASSIFICACAO(	C_EQUIPES.NOME_EQUIPE,
																			V_PONTUACAO,
																			V_QTD_JOGOS,
																			V_QTD_VITORIAS,
																			V_QTD_EMPATES,
																			V_QTD_DERROTAS,
																			V_GOLS_PRO,
																			V_GOLS_CONTRA,
																			V_GOLS_SALDO,
																			V_APROVEITAMENTO
																		 );	


	END LOOP;


RETURN V_RETORNO;
END;