/*

GOLS

*/




begin

PKG_JOGO.SP_INSERE_GOL_PARTIDA( 1,'Internacional',1,0,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 1,'Fluminense',3,0,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 1,'Chapecoense',0,0,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 1,'Atlético Mineiro',0,0,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 1,'São Paulo',3,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 1,'Bahia',1,2,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 1,'Atlético Paranaense',1,0,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 1,'Criciúma',1,2,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 1,'Flamengo',0,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 1,'Santos',1,1,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 2,'Coritiba',0,0,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 2,'Palmeiras',0,1,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 2,'Corinthians',2,0,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 2,'Vitória',2,2,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 2,'Botafogo',2,2,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 2,'Cruzeiro',1,1,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 2,'Goiás',1,0,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 2,'Sport',2,1,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 2,'Figueirense',0,2,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 2,'Grêmio',2,1,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 3,'São Paulo',2,2,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 3,'Atlético Paranaense',2,3,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 3,'Santos',0,0,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 3,'Fluminense',1,2,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 3,'Flamengo',4,2,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 3,'Criciúma',1,0,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 3,'Bahia',1,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 3,'Internacional',2,1,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 3,'Chapecoense',0,1,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 3,'Atlético Mineiro',0,1,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 4,'Palmeiras',2,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 4,'Internacional',2,1,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 4,'Botafogo',6,0,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 4,'Atlético Mineiro',2,1,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 4,'Fluminense',2,0,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 4,'Chapecoense',1,2,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 4,'São Paulo',1,1,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 4,'Bahia',1,1,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 4,'Figueirense',0,2,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 4,'Coritiba',0,1,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 5,'Goiás',2,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 5,'Cruzeiro',3,2,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 5,'Corinthians',0,1,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 5,'Atlético Paranaense',1,1,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 5,'Flamengo',0,2,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 5,'Grêmio',1,0,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 5,'Santos',1,2,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 5,'Criciúma',0,0,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 5,'Vitória',0,1,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 5,'Sport',1,0,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 6,'Coritiba',1,1,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 6,'Flamengo',1,1,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 6,'Cruzeiro',2,0,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 6,'Criciúma',1,0,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 6,'Corinthians',1,1,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 6,'Grêmio',2,1,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 6,'Fluminense',5,2,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 6,'Palmeiras',1,0,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 6,'Goiás',2,2,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 6,'Vitória',2,3,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 7,'Bahia',0,1,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 7,'São Paulo',1,0,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 7,'Figueirense',0,1,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 7,'Santos',0,0,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 7,'Sport',1,4,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 7,'Atlético Paranaense',2,0,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 7,'Chapecoense',2,0,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 7,'Botafogo',1,1,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 7,'Atlético Mineiro',0,0,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 7,'Internacional',1,3,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 8,'Sport',0,0,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 8,'Palmeiras',0,2,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 8,'Criciúma',1,0,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 8,'Internacional',2,0,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 8,'Goiás',0,0,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 8,'Corinthians',1,0,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 8,'Atlético Paranaense',2,2,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 8,'Atlético Mineiro',2,0,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 8,'Flamengo',1,1,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 8,'Bahia',0,2,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 9,'São Paulo',2,1,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 9,'Coritiba',3,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 9,'Vitória',0,1,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 9,'Grêmio',0,0,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 9,'Chapecoense',2,1,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 9,'Cruzeiro',3,0,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 9,'Figueirense',1,3,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 9,'Santos',2,0,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 9,'Fluminense',1,1,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 9,'Botafogo',1,0,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 10,'Coritiba',0,2,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 10,'Sport',1,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 10,'Grêmio',0,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 10,'Bahia',0,2,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 10,'Flamengo',1,2,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 10,'Criciúma',3,2,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 10,'Corinthians',2,1,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 10,'Santos',2,0,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 10,'Cruzeiro',3,1,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 10,'Chapecoense',1,1,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 11,'São Paulo',0,1,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 11,'Atlético Mineiro',1,1,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 11,'Figueirense',0,1,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 11,'Botafogo',1,0,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 11,'Vitória',0,0,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 11,'Palmeiras',1,2,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 11,'Internacional',4,0,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 11,'Atlético Paranaense',2,0,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 11,'Goiás',0,0,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 11,'Fluminense',1,0,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 12,'Santos',3,0,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 12,'Cruzeiro',5,0,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 12,'Criciúma',1,3,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 12,'Bahia',0,1,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 12,'Corinthians',2,0,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 12,'Atlético Paranaense',0,3,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 12,'Goiás',2,1,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 12,'Sport',2,1,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 12,'Flamengo',1,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 12,'Grêmio',2,3,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 13,'São Paulo',1,1,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 13,'Botafogo',1,1,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 13,'Vitória',2,1,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 13,'Figueirense',3,0,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 13,'Coritiba',0,0,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 13,'Palmeiras',1,1,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 13,'Chapecoense',1,0,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 13,'Fluminense',2,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 13,'Atlético Mineiro',3,1,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 13,'Internacional',1,0,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 14,'Bahia',1,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 14,'Criciúma',0,0,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 14,'Fluminense',1,1,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 14,'Internacional',2,0,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 14,'Santos',0,1,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 14,'Flamengo',1,0,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 14,'Atlético Paranaense',2,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 14,'São Paulo',3,1,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 14,'Chapecoense',0,1,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 14,'Atlético Mineiro',2,1,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 15,'Goiás',0,1,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 15,'Corinthians',1,1,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 15,'Grêmio',2,0,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 15,'Cruzeiro',3,0,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 15,'Palmeiras',1,2,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 15,'Vitória',0,0,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 15,'Coritiba',0,1,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 15,'Figueirense',2,2,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 15,'Botafogo',2,0,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 15,'Sport',1,1,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 16,'Figueirense',1,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 16,'Santos',2,0,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 16,'Sport',2,1,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 16,'Bahia',0,0,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 16,'Coritiba',2,0,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 16,'Flamengo',2,1,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 16,'Internacional',0,1,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 16,'Chapecoense',1,0,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 16,'Corinthians',5,2,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 16,'Cruzeiro',1,0,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 17,'Botafogo',1,0,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 17,'Atlético Mineiro',1,0,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 17,'Palmeiras',1,0,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 17,'Fluminense',4,0,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 17,'São Paulo',2,1,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 17,'Vitória',0,1,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 17,'Criciúma',0,2,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 17,'Grêmio',2,1,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 17,'Atlético Paranaense',0,0,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 17,'Goiás',0,1,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 18,'Cruzeiro',4,2,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 18,'Palmeiras',0,1,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 18,'Corinthians',1,1,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 18,'Figueirense',1,1,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 18,'Coritiba',0,0,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 18,'Sport',2,0,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 18,'Botafogo',1,0,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 18,'Grêmio',1,0,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 18,'Goiás',3,1,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 18,'Vitória',1,2,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 19,'Flamengo',0,1,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 19,'Santos',3,1,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 19,'Chapecoense',0,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 19,'Fluminense',3,3,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 19,'Atlético Mineiro',1,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 19,'Criciúma',0,0,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 19,'São Paulo',2,0,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 19,'Internacional',2,3,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 19,'Atlético Paranaense',1,1,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 19,'Bahia',0,0,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 20,'Figueirense',1,1,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 20,'Palmeiras',1,0,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 20,'Grêmio',1,0,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 20,'Sport',3,1,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 20,'Coritiba',3,0,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 20,'Botafogo',2,4,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 20,'Goiás',1,0,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 20,'Vitória',2,0,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 20,'Corinthians',1,0,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 20,'Cruzeiro',2,1,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 21,'Chapecoense',3,1,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 21,'Fluminense',3,0,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 21,'Santos',2,1,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 21,'Bahia',3,0,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 21,'Internacional',2,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 21,'Flamengo',1,0,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 21,'São Paulo',2,0,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 21,'Atlético Mineiro',0,0,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 21,'Criciúma',1,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 21,'Atlético Paranaense',2,0,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 22,'Vitória',3,1,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 22,'Cruzeiro',2,0,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 22,'Sport',0,0,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 22,'Figueirense',1,1,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 22,'Coritiba',3,1,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 22,'Botafogo',2,3,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 22,'Palmeiras',2,2,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 22,'Goiás',2,3,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 22,'Corinthians',1,1,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 22,'Grêmio',0,0,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 23,'Atlético Paranaense',0,1,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 23,'Criciúma',1,1,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 23,'Cruzeiro',2,3,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 23,'Corinthians',3,2,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 23,'Vitória',2,1,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 23,'Flamengo',1,1,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 23,'Sport',1,0,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 23,'Grêmio',1,0,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 23,'Santos',3,1,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 23,'Goiás',6,0,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 24,'Coritiba',1,2,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 24,'Internacional',3,0,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 24,'Bahia',1,0,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 24,'Chapecoense',3,0,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 24,'Figueirense',1,0,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 24,'São Paulo',2,2,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 24,'Fluminense',0,0,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 24,'Botafogo',1,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 24,'Palmeiras',2,0,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 24,'Atlético Mineiro',3,2,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 25,'Sport',0,0,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 25,'Chapecoense',1,1,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 25,'São Paulo',1,3,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 25,'Bahia',2,1,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 25,'Atlético Paranaense',1,0,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 25,'Botafogo',0,2,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 25,'Atlético Mineiro',2,0,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 25,'Santos',2,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 25,'Figueirense',3,1,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 25,'Internacional',4,2,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 26,'Palmeiras',4,2,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 26,'Vitória',2,1,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 26,'Coritiba',1,0,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 26,'Flamengo',0,1,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 26,'Fluminense',1,1,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 26,'Grêmio',0,1,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 26,'Corinthians',3,0,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 26,'Cruzeiro',2,1,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 26,'Criciúma',3,1,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 26,'Goiás',1,0,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 27,'São Paulo',1,0,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 27,'Coritiba',1,0,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 27,'Botafogo',0,1,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 27,'Vitória',2,2,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 27,'Figueirense',1,2,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 27,'Cruzeiro',0,1,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 27,'Grêmio',2,0,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 27,'Santos',1,0,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 27,'Fluminense',0,0,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 27,'Chapecoense',5,0,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 28,'Corinthians',1,1,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 28,'Goiás',3,0,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 28,'Palmeiras',2,1,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 28,'Bahia',0,1,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 28,'Flamengo',3,0,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 28,'Atlético Mineiro',1,0,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 28,'Internacional',2,1,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 28,'Sport',1,2,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 28,'Atlético Paranaense',3,0,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 28,'Criciúma',3,0,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 29,'Goiás',0,0,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 29,'Fluminense',4,2,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 29,'São Paulo',2,1,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 29,'Atlético Mineiro',1,0,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 29,'Figueirense',4,0,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 29,'Atlético Paranaense',2,1,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 29,'Palmeiras',1,3,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 29,'Internacional',1,2,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 29,'Botafogo',1,1,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 29,'Vitória',0,1,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 30,'Bahia',1,1,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 30,'Criciúma',0,1,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 30,'Cruzeiro',1,1,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 30,'Corinthians',2,1,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 30,'Flamengo',2,0,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 30,'Coritiba',2,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 30,'Grêmio',1,0,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 30,'Santos',0,1,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 30,'Chapecoense',0,0,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 30,'Sport',0,1,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 31,'Figueirense',1,1,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 31,'Palmeiras',1,1,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 31,'Fluminense',2,1,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 31,'Chapecoense',1,1,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 31,'Atlético Mineiro',3,2,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 31,'Vitória',3,1,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 31,'Coritiba',1,1,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 31,'Botafogo',2,1,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 31,'Internacional',2,0,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 31,'São Paulo',3,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 32,'Grêmio',1,0,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 32,'Goiás',0,2,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 32,'Corinthians',2,2,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 32,'Criciúma',1,2,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 32,'Santos',1,2,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 32,'Sport',1,0,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 32,'Cruzeiro',2,1,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 32,'Flamengo',3,0,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 32,'Atlético Paranaense',1,0,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 32,'Bahia',0,1,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 33,'Coritiba',1,0,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 33,'Palmeiras',0,2,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 33,'Botafogo',0,2,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 33,'Sport',2,2,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 33,'Vitória',1,2,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 33,'Figueirense',1,0,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 33,'Grêmio',4,1,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 33,'Cruzeiro',3,1,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 33,'Goiás',3,0,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 33,'Corinthians',1,0,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 34,'Criciúma',0,3,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 34,'Fluminense',1,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 34,'Atlético Paranaense',0,1,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 34,'Flamengo',3,2,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 34,'Santos',0,1,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 34,'Bahia',1,2,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 34,'Internacional',1,0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 34,'São Paulo',2,0,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 34,'Chapecoense',0,1,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 34,'Atlético Mineiro',1,1,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 35,'São Paulo',1,1,'Internacional');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 35,'Atlético Paranaense',1,1,'Santos');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 35,'Botafogo',0,1,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 35,'Vitória',1,1,'Coritiba');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 35,'Criciúma',0,1,'Bahia');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 35,'Goiás',0,1,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 35,'Palmeiras',0,2,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 35,'Atlético Mineiro',4,0,'Flamengo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 35,'Fluminense',1,4,'Chapecoense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 35,'Grêmio',1,2,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 36,'Internacional',2,1,'Atlético Mineiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 36,'Bahia',1,2,'Atlético Paranaense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 36,'Flamengo',1,1,'Criciúma');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 36,'Santos',0,1,'São Paulo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 36,'Sport',2,2,'Fluminense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 36,'Cruzeiro',2,1,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 36,'Figueirense',2,0,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 36,'Corinthians',1,0,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 36,'Coritiba',2,0,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 36,'Chapecoense',2,0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 37, 'Internacional', 3, 1,'Palmeiras');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 37, 'Criciúma', 2, 2,'Sport');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 37, 'Flamengo', 4, 0,'Vitória');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 37, 'São Paulo', 1, 1,'Figueirense');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 37, 'Santos', 2, 0,'Botafogo');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 37, 'Chapecoense', 1, 1,'Cruzeiro');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 37, 'Fluminense', 5, 2,'Corinthians');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 37, 'Atlético Paranaense', 1, 0,'Goiás');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 37, 'Bahia', 1, 0,'Grêmio');
PKG_JOGO.SP_INSERE_GOL_PARTIDA( 37, 'Atlético Mineiro', 1, 2,'Coritiba');

end;